#ifndef CHONK_BNE_TRACE_PROTOCOL_H
#define CHONK_BNE_TRACE_PROTOCOL_H

#define CHONK_BNE_TRACE_PROTOCOL 2
#define CHONK_BNE_TRACE_ENV "CHONK_BNE_TRACE"
#define CHONK_BNE_TRACE_DEFAULT "bne-trace.jsonl"

#define CHONK_BNE_STATE_ENV "CHONK_BNE_STATE"
#define CHONK_BNE_STATE_MAGIC "BNESTATE"
#define CHONK_BNE_STATE_MAJOR 1
#define CHONK_BNE_STATE_MINOR 1
#define CHONK_BNE_STATE_FLAG_UNIT_DELTAS 0x00000001UL
#define CHONK_BNE_STATE_FLAG_BULLET_DELTAS 0x00000002UL
#define CHONK_BNE_STATE_FLAG_PLAYER_SIM 0x00000004UL
#define CHONK_BNE_STATE_FLAG_MAP_DELTAS 0x00000008UL
#define CHONK_BNE_STATE_FLAGS (CHONK_BNE_STATE_FLAG_UNIT_DELTAS \
        | CHONK_BNE_STATE_FLAG_BULLET_DELTAS \
        | CHONK_BNE_STATE_FLAG_PLAYER_SIM \
        | CHONK_BNE_STATE_FLAG_MAP_DELTAS)

#endif
