apiVersion: v1
kind: Service
metadata:
  name: chonkcraft-matchmaker
  namespace: chonk-mp
  labels:
    app.kubernetes.io/name: chonkcraft-matchmaker
    app.kubernetes.io/part-of: chonkcraft
spec:
  selector:
    app.kubernetes.io/name: chonkcraft-matchmaker
  ports:
    - name: http
      port: 9092
      targetPort: http
