package net.chonkbase.chonkcraft.engine.script;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import net.chonkbase.chonkcraft.engine.GameData;
import net.chonkbase.chonkcraft.engine.ui.UnitButton;
import net.chonkbase.chonkcraft.engine.unit.UnitType;
import net.chonkbase.chonkcraft.engine.upgrade.Upgrade;

/**
 * Writes the game's definitions out as Java source.
 *
 * <p>The scripts are read once, here, and what they describe is emitted as
 * code. A build that runs this does not need a retired scripting language interpreter or a ChonkCraft
 * checkout to know what a footman costs: it needs a compiler, and after that
 * nothing at all.
 *
 * <p>What is generated is data, not behaviour. The buttons, the icon frames,
 * the tech tree, the upgrades and the unit roster are tables that the scripts
 * happen to write as code; the scripts that are genuinely programs, the AI
 * ones and the mission triggers, stay interpreted, because turning a program
 * into a table loses the program.
 *
 * <p>The interpreter is still the definition of correct. This writes what the
 * interpreter found, and a test compares the two, so the generated code cannot
 * drift into being a second and disagreeing source of truth.
 */
public final class DefinitionWriter {

    /** The package the generated classes live in. */
    public static final String PACKAGE = "net.chonkbase.chonkcraft.engine.generated";

    private final GameData data;

    public DefinitionWriter(GameData data) {
        this.data = data;
    }

    /**
     * Writes every generated class under a source root.
     *
     * @param root      the source directory, such as {@code engine/src/main/java}
     * @param tilesetName which tileset's icon frames to record
     * @return the files written
     */
    public List<Path> writeAll(Path root, String tilesetName) throws IOException {
        Path directory = root.resolve(PACKAGE.replace('.', '/'));
        Files.createDirectories(directory);

        List<Path> written = new java.util.ArrayList<>();
        written.add(write(directory.resolve("GeneratedButtons.java"), this::writeButtons));
        written.add(write(directory.resolve("GeneratedIcons.java"),
                out -> writeIcons(out, tilesetName)));
        written.add(write(directory.resolve("GeneratedDependencies.java"), this::writeDependencies));
        written.add(write(directory.resolve("GeneratedUpgrades.java"), this::writeUpgrades));
        written.add(write(directory.resolve("GeneratedUnitTypes.java"), this::writeUnitTypes));
        written.add(write(directory.resolve("GeneratedMissiles.java"), this::writeMissiles));
        written.add(write(directory.resolve("GeneratedSpells.java"), this::writeSpells));
        return written;
    }

    /** Writes only the spell snapshot, avoiding unrelated generated-file churn. */
    public Path writeSpells(Path root) throws IOException {
        Path directory = root.resolve(PACKAGE.replace('.', '/'));
        Files.createDirectories(directory);
        return write(directory.resolve("GeneratedSpells.java"), this::writeSpells);
    }

    /** Writes only the complete unit roster and animation bank. */
    public List<Path> writeRoster(Path root) throws IOException {
        Path directory = root.resolve(PACKAGE.replace('.', '/'));
        Files.createDirectories(directory);
        return List.of(
                write(directory.resolve("GeneratedAnimations.java"), this::writeAnimations),
                write(directory.resolve("GeneratedUnitRoster.java"), this::writeUnitRoster));
    }

    /** What a generator does with an open writer. */
    private interface Body {
        void write(Writer out) throws IOException;
    }

    private static Path write(Path file, Body body) throws IOException {
        try (Writer out = Files.newBufferedWriter(file, StandardCharsets.UTF_8)) {
            body.write(out);
        }
        return file;
    }

    private void header(Writer out, String className, String summary) throws IOException {
        out.write("package " + PACKAGE + ";\n\n");
        out.write("/**\n");
        out.write(" * " + summary + "\n");
        out.write(" *\n");
        out.write(" * <p>Generated by {@code DefinitionWriter} from the documented legacy\n");
        out.write(" * declarations. Provenance remains with the source; generation is not a\n");
        out.write(" * retail-authority claim. Do not edit: change the source or writer.\n");
        out.write(" */\n");
        out.write("public final class " + className + " {\n\n");
        out.write("    private " + className + "() {\n    }\n\n");
    }

    private void writeButtons(Writer out) throws IOException {
        header(out, "GeneratedButtons",
                "Every command-panel button the game defines, as the scripts declare them.");
        out.write("    /** One button, including presentation and availability metadata. */\n");
        out.write("    public record Row(int pos, int level, String icon, String action,\n");
        out.write("            String value, String allowed, java.util.List<String> allowArg,\n");
        out.write("            String popup, String key, String hint,\n");
        out.write("            java.util.List<String> forUnits) {}\n\n");
        out.write("    public static final java.util.List<Row> ROWS = java.util.List.of(\n");

        List<UnitButton> buttons = data.userInterface("summer").buttons().all();
        for (int i = 0; i < buttons.size(); i++) {
            UnitButton button = buttons.get(i);
            out.write("        new Row(" + button.pos() + ", " + button.level() + ", "
                    + quote(button.icon()) + ", " + quote(button.action()) + ", "
                    + quote(button.value()) + ", " + quote(button.allowed()) + ", "
                    + strings(button.allowArg()) + ", " + quote(button.popup()) + ", "
                    + quote(button.key()) + ", "
                    + quote(button.hint()) + ", " + strings(button.forUnits()) + ")");
            out.write(i + 1 < buttons.size() ? ",\n" : "\n");
        }
        out.write("    );\n}\n");
    }

    private void writeIcons(Writer out, String tilesetName) throws IOException {
        header(out, "GeneratedIcons", "Icon names and the frame each draws.");
        out.write("    /** The tileset these frames index. */\n");
        out.write("    public static final String TILESET = " + quote(tilesetName) + ";\n\n");
        out.write("    public static final java.util.Map<String, Integer> FRAMES =\n");
        out.write("            java.util.Map.ofEntries(\n");

        // Map.copyOf and Map.ofEntries do not promise iteration order. Sort the
        // generated source so two JDKs cannot turn an identical icon registry
        // into different bytes.
        Map<String, Integer> frames = new java.util.TreeMap<>(
                data.userInterface(tilesetName).icons().frames());
        int i = 0;
        for (Map.Entry<String, Integer> entry : frames.entrySet()) {
            out.write("        java.util.Map.entry(" + quote(entry.getKey()) + ", "
                    + entry.getValue() + ")");
            out.write(++i < frames.size() ? ",\n" : "\n");
        }
        out.write("    );\n}\n");
    }

    private void writeDependencies(Writer out) throws IOException {
        header(out, "GeneratedDependencies",
                "The tech tree: what a player must have before something is available.");
        out.write("    /** Alternatives; any one satisfied set will do. */\n");
        out.write("    public static final java.util.Map<String, "
                + "java.util.List<java.util.List<String>>> RULES = java.util.Map.ofEntries(\n");

        var rules = data.upgrades().dependencies();
        List<String> targets = new java.util.ArrayList<>();
        for (UnitType type : data.unitTypes().types().values()) {
            if (!rules.alternativesFor(type.ident()).isEmpty()) {
                targets.add(type.ident());
            }
        }
        for (Upgrade upgrade : data.upgrades().upgrades().all().values()) {
            if (!rules.alternativesFor(upgrade.ident()).isEmpty()) {
                targets.add(upgrade.ident());
            }
        }
        java.util.Collections.sort(targets);
        for (int i = 0; i < targets.size(); i++) {
            String target = targets.get(i);
            out.write("        java.util.Map.entry(" + quote(target) + ", java.util.List.of(");
            List<List<String>> alternatives = rules.alternativesFor(target);
            for (int a = 0; a < alternatives.size(); a++) {
                out.write(strings(alternatives.get(a)));
                if (a + 1 < alternatives.size()) {
                    out.write(", ");
                }
            }
            out.write("))");
            out.write(i + 1 < targets.size() ? ",\n" : "\n");
        }
        out.write("    );\n}\n");
    }

    private void writeUpgrades(Writer out) throws IOException {
        header(out, "GeneratedUpgrades", "The upgrades, their costs and what they change.");
        out.write("    /** One upgrade: what it costs, and the stat changes it applies. */\n");
        out.write("    public record Row(String ident, java.util.Map<String, Integer> costs,\n");
        out.write("            java.util.Map<String, Integer> changes,\n");
        out.write("            java.util.List<String> appliesTo, String convertTo) {}\n\n");
        out.write("    public static final java.util.List<Row> ROWS = java.util.List.of(\n");

        var upgrades = new java.util.ArrayList<>(data.upgrades().upgrades().all().values());
        upgrades.sort(java.util.Comparator.comparing(Upgrade::ident));
        for (int i = 0; i < upgrades.size(); i++) {
            Upgrade upgrade = upgrades.get(i);
            out.write("        new Row(" + quote(upgrade.ident()) + ", ");
            writeIntMap(out, upgrade.costs(), resource -> resource.name().toLowerCase(Locale.ROOT));
            out.write(", ");
            writeIntMap(out, upgrade.changes(), stat -> stat.name().toLowerCase(Locale.ROOT));
            out.write(", " + strings(upgrade.appliesTo()) + ", "
                    + quote(upgrade.convertTo()) + ")");
            out.write(i + 1 < upgrades.size() ? ",\n" : "\n");
        }
        out.write("    );\n}\n");
    }

    private void writeUnitTypes(Writer out) throws IOException {
        header(out, "GeneratedUnitTypes", "The unit roster and the stats each type carries.");
        out.write("    /** One unit type. Fields are the ones the simulation reads. */\n");
        out.write("    public record Row(String ident, String name, int hitPoints, int armor,\n");
        out.write("            int basicDamage, int piercingDamage, int minAttackRange,\n");
        out.write("            int maxAttackRange, int sightRange, int speed, int mana,\n");
        out.write("            int manaStart,\n");
        out.write("            int tileWidth, int tileHeight, int repairRange, int repairHp,\n");
        out.write("            boolean building, boolean canAttack, boolean landUnit,\n");
        out.write("            boolean seaUnit, boolean airUnit,\n");
        out.write("            java.util.Map<String, Integer> costs) {}\n\n");
        out.write("    public static final java.util.List<Row> ROWS = java.util.List.of(\n");

        var types = new java.util.ArrayList<>(data.unitTypes().types().values());
        types.sort(java.util.Comparator.comparing(UnitType::ident));
        for (int i = 0; i < types.size(); i++) {
            UnitType type = types.get(i);
            out.write("        new Row(" + quote(type.ident()) + ", " + quote(type.name()) + ", "
                    + type.hitPoints() + ", " + type.armor() + ", "
                    + type.basicDamage() + ", " + type.piercingDamage() + ", "
                    + type.minAttackRange() + ", " + type.maxAttackRange() + ", "
                    + type.sightRange() + ", " + type.speed() + ", " + type.mana() + ", "
                    + type.manaStart() + ", "
                    + type.tileWidth() + ", " + type.tileHeight() + ", "
                    + type.repairRange() + ", " + type.repairHp() + ", "
                    + type.building() + ", " + type.canAttack() + ", "
                    + type.landUnit() + ", " + type.seaUnit() + ", " + type.airUnit() + ", ");
            writeIntMap(out, type.costs(), resource -> resource.name().toLowerCase(Locale.ROOT));
            out.write(")");
            out.write(i + 1 < types.size() ? ",\n" : "\n");
        }
        out.write("    );\n}\n");
    }

    private void writeAnimations(Writer out) throws IOException {
        header(out, "GeneratedAnimations", "Every animation program used by the BNE roster.");
        out.write("    public static java.util.Map<String, "
                + "net.chonkbase.chonkcraft.engine.animation.AnimationSet> sets() {\n");
        out.write("        var result = new java.util.LinkedHashMap<String, "
                + "net.chonkbase.chonkcraft.engine.animation.AnimationSet>();\n");
        var sets = new java.util.ArrayList<>(data.animationSets().sets().values());
        sets.sort(java.util.Comparator.comparing(
                net.chonkbase.chonkcraft.engine.animation.AnimationSet::name));
        for (int i = 0; i < sets.size(); i++) {
            out.write("        result.put(" + quote(sets.get(i).name()) + ", set" + i + "());\n");
        }
        out.write("        return result;\n    }\n\n");
        for (int setIndex = 0; setIndex < sets.size(); setIndex++) {
            var set = sets.get(setIndex);
            out.write("    private static net.chonkbase.chonkcraft.engine.animation.AnimationSet set"
                    + setIndex + "() {\n");
            out.write("        var set = new net.chonkbase.chonkcraft.engine.animation.AnimationSet("
                    + quote(set.name()) + ");\n");
            var states = new java.util.ArrayList<>(set.states());
            states.sort(java.util.Comparator.comparing(Enum::name));
            for (var state : states) {
                var animation = set.get(state);
                out.write("        set.put(net.chonkbase.chonkcraft.engine.animation.AnimationSet.State."
                        + state.name() + ", new net.chonkbase.chonkcraft.engine.animation.Animation("
                        + quote(animation.name()) + ", java.util.List.of(\n");
                for (int i = 0; i < animation.instructions().size(); i++) {
                    var instruction = animation.instructions().get(i);
                    out.write("            new net.chonkbase.chonkcraft.engine.animation.Animation.Instruction("
                            + "net.chonkbase.chonkcraft.engine.animation.Animation.Kind."
                            + instruction.kind().name() + ", " + instruction.value() + ", "
                            + quote(instruction.operand()) + ")");
                    out.write(i + 1 < animation.instructions().size() ? ",\n" : "\n");
                }
                out.write("        )));\n");
            }
            out.write("        return set;\n    }\n\n");
        }
        out.write("}\n");
    }

    private void writeUnitRoster(Writer out) throws IOException {
        header(out, "GeneratedUnitRoster", "The complete typed BNE unit roster.");
        out.write("    public static java.util.Map<String, "
                + "net.chonkbase.chonkcraft.engine.unit.UnitType> types() {\n");
        out.write("        var result = new java.util.LinkedHashMap<String, "
                + "net.chonkbase.chonkcraft.engine.unit.UnitType>();\n");
        var types = new java.util.ArrayList<>(data.unitTypes().types().values());
        types.sort(java.util.Comparator.comparing(UnitType::ident));
        for (int i = 0; i < types.size(); i++) {
            out.write("        result.put(" + quote(types.get(i).ident()) + ", unit" + i + "());\n");
        }
        out.write("        return result;\n    }\n\n");
        for (int i = 0; i < types.size(); i++) {
            writeUnit(out, types.get(i), i);
        }
        out.write("}\n");
    }

    private static void writeUnit(Writer out, UnitType t, int index) throws IOException {
        out.write("    private static net.chonkbase.chonkcraft.engine.unit.UnitType unit"
                + index + "() {\n");
        out.write("        var t = new net.chonkbase.chonkcraft.engine.unit.UnitType("
                + quote(t.ident()) + ");\n");
        out.write("        net.chonkbase.chonkcraft.engine.unit.ResourceInfo r;\n");
        set(out, "Name", quote(t.name()));
        set(out, "ImageFile", quote(t.imageFile()));
        out.write("        t.setImageSize(" + t.imageWidth() + ", " + t.imageHeight() + ");\n");
        set(out, "Animations", quote(t.animations()));
        set(out, "NumDirections", t.numDirections());
        set(out, "Icon", quote(t.icon()));
        set(out, "Construction", quote(t.construction()));
        set(out, "Corpse", quote(t.corpse()));
        set(out, "DrawLevel", t.drawLevel());
        out.write("        t.setTileSize(" + t.tileWidth() + ", " + t.tileHeight() + ");\n");
        out.write("        t.setBoxSize(" + t.boxWidth() + ", " + t.boxHeight() + ");\n");
        set(out, "Elevated", t.elevated());
        set(out, "ShadowFile", quote(t.shadowFile()));
        out.write("        t.setShadowSize(" + t.shadowWidth() + ", " + t.shadowHeight() + ");\n");
        out.write("        t.setShadowOffset(" + t.shadowOffsetX() + ", " + t.shadowOffsetY() + ");\n");
        set(out, "ShadowSpriteFrame", t.shadowSpriteFrame());
        set(out, "HitPoints", t.hitPoints()); set(out, "Mana", t.mana());
        set(out, "ManaStart", t.manaStart()); set(out, "Armor", t.armor());
        set(out, "BasicDamage", t.basicDamage()); set(out, "PiercingDamage", t.piercingDamage());
        set(out, "SightRange", t.sightRange()); set(out, "MaxAttackRange", t.maxAttackRange());
        set(out, "MinAttackRange", t.minAttackRange()); set(out, "Speed", t.speed());
        set(out, "Priority", t.priority()); set(out, "Points", t.points());
        set(out, "Demand", t.demand()); set(out, "Supply", t.supply());
        set(out, "Level", t.level()); set(out, "RepairHp", t.repairHp());
        set(out, "RepairRange", t.repairRange()); set(out, "Missile", quote(t.missile()));
        set(out, "ReactRangePerson", t.reactRangePerson());
        set(out, "ReactRangeComputer", t.reactRangeComputer());
        set(out, "RandomMovementProbability", t.randomMovementProbability());
        set(out, "RandomMovementDistance", t.randomMovementDistance());
        set(out, "UnitTypeClass", quote(t.unitTypeClass()));
        set(out, "MaxOnBoard", t.maxOnBoard()); set(out, "ClicksToExplode", t.clicksToExplode());
        set(out, "NeutralMinimapColour", t.neutralMinimapColour());
        for (String flag : t.canTransport_()) {
            out.write("        t.canTransport_().add(" + quote(flag) + ");\n");
        }
        set(out, "Building", t.building()); set(out, "VisibleUnderFog", t.visibleUnderFog());
        set(out, "LandUnit", t.landUnit()); set(out, "SeaUnit", t.seaUnit());
        set(out, "AirUnit", t.airUnit()); set(out, "ShoreBuilding", t.shoreBuilding());
        set(out, "BuilderOutside", t.builderOutside()); set(out, "CanAttack", t.canAttack());
        set(out, "CanTargetLand", t.canTargetLand()); set(out, "CanTargetSea", t.canTargetSea());
        set(out, "CanTargetAir", t.canTargetAir());
        set(out, "SelectableByRectangle", t.selectableByRectangle());
        set(out, "Explosion", quote(t.explosion())); set(out, "Indestructible", t.indestructible());
        set(out, "Wall", t.wall()); set(out, "Coward", t.coward());
        set(out, "DetectCloak", t.detectCloak()); set(out, "PermanentCloak", t.permanentCloak());
        set(out, "Vanishes", t.vanishes()); set(out, "Revealer", t.revealer());
        set(out, "NonSolid", t.nonSolid()); set(out, "GroundAttack", t.groundAttack());
        set(out, "SideAttack", t.sideAttack()); set(out, "RightMouseAction", quote(t.rightMouseAction()));
        set(out, "RotationSpeed", t.rotationSpeed()); set(out, "OnReadyExplores", t.onReadyExplores());
        if (t.givesResource() != null) {
            out.write("        t.setGivesResource(net.chonkbase.chonkcraft.engine.unit.UnitType.Resource."
                    + t.givesResource().name() + ");\n");
        }
        set(out, "CanHarvest", t.canHarvest());
        writeStringMap(out, "tilesetImageFiles", t.tilesetImageFiles());
        writeResourceIntMap(out, "costs", t.costs());
        writeResourceIntMap(out, "repairCosts", t.repairCosts());
        writeResourceIntMap(out, "improveProduction", t.improveProduction());
        for (var resource : t.stores()) {
            out.write("        t.stores().add(net.chonkbase.chonkcraft.engine.unit.UnitType.Resource."
                    + resource.name() + ");\n");
        }
        writeStringMap(out, "sounds", t.sounds());
        for (var entry : t.gathering().entrySet()) {
            var r = entry.getValue();
            out.write("        r = new net.chonkbase.chonkcraft.engine.unit.ResourceInfo("
                    + "net.chonkbase.chonkcraft.engine.unit.UnitType.Resource."
                    + entry.getKey().name() + ");\n");
            out.write("        r.setFileWhenLoaded(" + quote(r.fileWhenLoaded()) + ");\n");
            out.write("        r.setFileWhenEmpty(" + quote(r.fileWhenEmpty()) + ");\n");
            out.write("        r.setCapacity(" + r.capacity() + ");\n");
            out.write("        r.setStep(" + r.step() + ");\n");
            out.write("        r.setWaitAtResource(" + r.waitAtResource() + ");\n");
            out.write("        r.setWaitAtDepot(" + r.waitAtDepot() + ");\n");
            out.write("        r.setTerrainHarvester(" + r.terrainHarvester() + ");\n");
            out.write("        r.setRefineryHarvester(" + r.refineryHarvester() + ");\n");
            out.write("        r.setHarvestFromOutside(" + r.harvestFromOutside() + ");\n");
            out.write("        t.gathering().put(r.resource(), r);\n");
        }
        for (var andList : t.buildingRules()) {
            out.write("        t.buildingRules().add(java.util.List.of(");
            for (int i = 0; i < andList.size(); i++) {
                var rule = andList.get(i);
                if (rule instanceof net.chonkbase.chonkcraft.engine.unit.BuildRestriction.OnTop top) {
                    out.write("new net.chonkbase.chonkcraft.engine.unit.BuildRestriction.OnTop("
                            + quote(top.parentIdent()) + ", " + top.replaceOnBuild() + ", "
                            + top.replaceOnDie() + ")");
                } else if (rule instanceof net.chonkbase.chonkcraft.engine.unit.BuildRestriction.Distance d) {
                    out.write("new net.chonkbase.chonkcraft.engine.unit.BuildRestriction.Distance("
                            + quote(d.restrictIdent()) + ", " + d.distance() + ", "
                            + "net.chonkbase.chonkcraft.engine.unit.BuildRestriction.Comparison."
                            + d.comparison().name() + ", " + d.checkBuilder() + ", "
                            + d.diagonal() + ")");
                } else if (rule instanceof net.chonkbase.chonkcraft.engine.unit.BuildRestriction.Unsupported u) {
                    out.write("new net.chonkbase.chonkcraft.engine.unit.BuildRestriction.Unsupported("
                            + quote(u.kind()) + ")");
                }
                if (i + 1 < andList.size()) out.write(", ");
            }
            out.write("));\n");
        }
        out.write("        return t;\n    }\n\n");
    }

    private static void set(Writer out, String property, Object value) throws IOException {
        out.write("        t.set" + property + "(" + value + ");\n");
    }

    private static void writeStringMap(Writer out, String method, Map<String, String> map)
            throws IOException {
        for (var entry : map.entrySet()) {
            out.write("        t." + method + "().put(" + quote(entry.getKey()) + ", "
                    + quote(entry.getValue()) + ");\n");
        }
    }

    private static void writeResourceIntMap(Writer out, String method,
            Map<UnitType.Resource, Integer> map) throws IOException {
        for (var entry : map.entrySet()) {
            out.write("        t." + method + "().put("
                    + "net.chonkbase.chonkcraft.engine.unit.UnitType.Resource."
                    + entry.getKey().name() + ", " + entry.getValue() + ");\n");
        }
    }

    private void writeMissiles(Writer out) throws IOException {
        header(out, "GeneratedMissiles",
                "Every projectile definition and damaged-building fire row.");
        out.write("    public record BurnRow(int percent, String missile) {}\n\n");
        out.write("    public static final java.util.List<"
                + "net.chonkbase.chonkcraft.engine.missile.MissileType> TYPES = "
                + "java.util.List.of(\n");
        var missiles = new java.util.ArrayList<>(data.missiles().types().values());
        missiles.sort(java.util.Comparator.comparing(
                net.chonkbase.chonkcraft.engine.missile.MissileType::ident));
        for (int i = 0; i < missiles.size(); i++) {
            var m = missiles.get(i);
            out.write("        new net.chonkbase.chonkcraft.engine.missile.MissileType("
                    + quote(m.ident()) + ", " + quote(m.sprite()) + ", "
                    + "net.chonkbase.chonkcraft.engine.missile.MissileClass."
                    + m.missileClass().name() + ", "
                    + m.frameWidth() + ", " + m.frameHeight() + ", " + m.frames() + ", "
                    + m.directions() + ", " + m.speed() + ", " + m.sleep() + ", "
                    + m.range() + ", " + m.splashFactor() + ", " + m.drawLevel() + ", "
                    + quote(m.impactMissile()) + ", " + quote(m.impactSound()) + ", "
                    + m.canHitOwner() + ", " + m.numBounces() + ", " + m.damage() + ", "
                    + m.correctSplashDamage() + ", " + quote(m.firedSound()) + ", "
                    + m.damageRandom() + ", " + m.blizzardSpeed() + ")");
            out.write(i + 1 < missiles.size() ? ",\n" : "\n");
        }
        out.write("    );\n\n");
        out.write("    public static final java.util.List<BurnRow> BURNING = java.util.List.of(\n");
        var frames = data.missiles().burningBuildings().frames();
        for (int i = 0; i < frames.size(); i++) {
            var frame = frames.get(i);
            out.write("        new BurnRow(" + frame.percent() + ", "
                    + quote(frame.missile() == null ? null : frame.missile().ident()) + ")");
            out.write(i + 1 < frames.size() ? ",\n" : "\n");
        }
        out.write("    );\n}\n");
    }

    private void writeSpells(Writer out) throws IOException {
        header(out, "GeneratedSpells", "Every runtime spell and its native effect arguments.");
        out.write("    public record EffectRow(String kind, String what, int amount, "
                + "java.util.Map<String, Object> args) {}\n\n");
        out.write("    public record Row(String ident, String name, int manaCost, int range, "
                + "String target, String soundWhenCast, String dependUpgrade, "
                + "boolean organicOnly, boolean allowBuildings, boolean autoCastable, "
                + "java.util.List<EffectRow> effects) {}\n\n");
        out.write("    public static final java.util.List<Row> ROWS = java.util.List.of(\n");
        var spells = new java.util.ArrayList<>(data.spells().spells().all().values());
        spells.sort(java.util.Comparator.comparing(
                net.chonkbase.chonkcraft.engine.spell.Spell::ident));
        for (int i = 0; i < spells.size(); i++) {
            var spell = spells.get(i);
            out.write("        new Row(" + quote(spell.ident()) + ", " + quote(spell.name())
                    + ", " + spell.manaCost() + ", " + spell.range() + ", "
                    + quote(spell.target().name()) + ", " + quote(spell.soundWhenCast())
                    + ", " + quote(spell.dependUpgrade()) + ", " + spell.organicOnly()
                    + ", " + spell.allowBuildings() + ", " + spell.autoCastable()
                    + ", java.util.List.of(");
            for (int e = 0; e < spell.effects().size(); e++) {
                var effect = spell.effects().get(e);
                out.write("new EffectRow(" + quote(effect.kind().name()) + ", "
                        + quote(effect.what()) + ", " + effect.amount() + ", ");
                writeObject(out, effect.args());
                out.write(")");
                if (e + 1 < spell.effects().size()) {
                    out.write(", ");
                }
            }
            out.write("))");
            out.write(i + 1 < spells.size() ? ",\n" : "\n");
        }
        out.write("    );\n}\n");
    }

    private static void writeObject(Writer out, Object value) throws IOException {
        if (value == null) {
            out.write("null");
        } else if (value instanceof String text) {
            out.write(quote(text));
        } else if (value instanceof Number || value instanceof Boolean) {
            out.write(String.valueOf(value));
        } else if (value instanceof List<?> list) {
            out.write("java.util.List.of(");
            for (int i = 0; i < list.size(); i++) {
                writeObject(out, list.get(i));
                if (i + 1 < list.size()) {
                    out.write(", ");
                }
            }
            out.write(")");
        } else if (value instanceof Map<?, ?> map) {
            if (map.isEmpty()) {
                out.write("java.util.Map.of()");
                return;
            }
            out.write("java.util.Map.ofEntries(");
            var entries = new java.util.ArrayList<>(map.entrySet());
            entries.sort(java.util.Comparator.comparing(entry -> String.valueOf(entry.getKey())));
            for (int i = 0; i < entries.size(); i++) {
                var entry = entries.get(i);
                out.write("java.util.Map.entry(");
                writeObject(out, String.valueOf(entry.getKey()));
                out.write(", ");
                writeObject(out, entry.getValue());
                out.write(")");
                if (i + 1 < entries.size()) {
                    out.write(", ");
                }
            }
            out.write(")");
        } else {
            throw new IllegalArgumentException("Cannot generate spell value "
                    + value.getClass().getName());
        }
    }

    /** A map keyed by an enum, written with the key's lower-case name. */
    private static <K> void writeIntMap(Writer out, Map<K, Integer> map,
            java.util.function.Function<K, String> name) throws IOException {
        if (map.isEmpty()) {
            out.write("java.util.Map.of()");
            return;
        }
        out.write("java.util.Map.ofEntries(");
        int i = 0;
        for (Map.Entry<K, Integer> entry : map.entrySet()) {
            out.write("java.util.Map.entry(" + quote(name.apply(entry.getKey())) + ", "
                    + entry.getValue() + ")");
            if (++i < map.size()) {
                out.write(", ");
            }
        }
        out.write(")");
    }

    private static String strings(List<String> values) {
        if (values == null || values.isEmpty()) {
            return "java.util.List.of()";
        }
        StringBuilder out = new StringBuilder("java.util.List.of(");
        for (int i = 0; i < values.size(); i++) {
            out.append(quote(values.get(i)));
            if (i + 1 < values.size()) {
                out.append(", ");
            }
        }
        return out.append(')').toString();
    }

    /** A Java string literal, or {@code null} for a missing value. */
    static String quote(String value) {
        if (value == null) {
            return "null";
        }
        StringBuilder out = new StringBuilder("\"");
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (c < 0x20 || c > 0x7E) {
                        out.append(String.format("\\u%04x", (int) c));
                    } else {
                        out.append(c);
                    }
                }
            }
        }
        return out.append('"').toString();
    }
}
