apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chonkcraft-updates
  namespace: chonkcraft-updates
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 2Gi
