#!/usr/bin/env python3
"""Generate the Battle.net Edition MPQ asset index from ChonkCraft's wartool.h.

The BNE-specific Q rows name files inside INSTALL.EXE and the War2Dat.mpq
stored inside it. This emits only rows with literal destination names; the
remaining macro-based rows are text tables already represented by the four
TOME archives.

Usage:
    tools/extract-battle-net-index.py ../chonkcraft/wartool.h \
        data/src/main/resources/chonkcraft/battle-net-assets.tsv
"""

import re
import sys


ROW = re.compile(
    r'^\{Q,\s*8,\s*"([^"]+)",\s*([^,]+),\s*([^,]+),'
    r'\s*[^,]+,\s*[^,]+,\s*"([^"]+)",\s*"([^"]+)"\},?'
)


def kind_of(destination, argument):
    """Classify a wartool destination by what the pack needs to do with it."""
    lower = destination.lower()
    if lower.startswith("sounds/") or lower.startswith("campaigns/") and lower.endswith(".wav"):
        return "sound"
    if lower.startswith("maps/") and lower.endswith(".pud"):
        return "map"
    if lower.startswith("videos/") or argument == "'V'":
        return "video"
    if lower.startswith("music/") and lower.endswith(".wav"):
        return "music"
    if argument in {"'X'", "'L'", "'S'", "'?'"}:
        return "text"
    return "binary"


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    source, target = sys.argv[1], sys.argv[2]

    rows = []
    with open(source, encoding="latin-1") as handle:
        for line in handle:
            match = ROW.match(line)
            if not match:
                continue
            destination, local, argument, archive, archived = match.groups()
            # The first row creates the local nested archive. The reader does
            # that internally, so it is not itself a game asset.
            if destination.lower() == "war2dat.mpq":
                continue
            rows.append((
                kind_of(destination, argument),
                "inner" if local.strip() == "1" else "outer",
                destination,
                archive,
                archived.replace("\\\\", "\\"),
            ))

    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(
            "# Generated by tools/extract-battle-net-index.py from chonkcraft/wartool.h\n"
        )
        handle.write("# kind\tcontainer\tdestination\tarchive\tarchived-path\n")
        for row in rows:
            handle.write("\t".join(row) + "\n")

    counts = {}
    for row in rows:
        counts[row[0]] = counts.get(row[0], 0) + 1
    print(
        f"wrote {len(rows)} rows to {target}: "
        + ", ".join(f"{key}={value}" for key, value in sorted(counts.items()))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
